/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author LAB03M06
 */
public class jokenPo extends javax.swing.JFrame {

    int contPL = 0;
    int contPC = 0;

    /**
     * Creates new form jokenPo
     */
    public jokenPo() {
        initComponents();
        reiniciar.setVisible(false);
        placarPL.setText("Jogador: " + contPL);
        placarPC.setText("PC: " + contPC);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        pedra = new org.edisoncor.gui.panel.PanelImage();
        papel = new org.edisoncor.gui.panel.PanelImage();
        tesoura = new org.edisoncor.gui.panel.PanelImage();
        btnpedra = new javax.swing.JButton();
        btntesoura = new javax.swing.JButton();
        btnpapel = new javax.swing.JButton();
        pedraPc = new org.edisoncor.gui.panel.PanelImage();
        tesouraPc = new org.edisoncor.gui.panel.PanelImage();
        papelPc = new org.edisoncor.gui.panel.PanelImage();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        reiniciar = new javax.swing.JButton();
        resultado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        placarPL = new javax.swing.JLabel();
        placarPC = new javax.swing.JLabel();
        sair = new org.edisoncor.gui.button.ButtonNice();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        pedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pedra.png"))); // NOI18N

        javax.swing.GroupLayout pedraLayout = new javax.swing.GroupLayout(pedra);
        pedra.setLayout(pedraLayout);
        pedraLayout.setHorizontalGroup(
            pedraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pedraLayout.setVerticalGroup(
            pedraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(pedra);
        pedra.setBounds(160, 260, 100, 100);

        papel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/papel.png"))); // NOI18N

        javax.swing.GroupLayout papelLayout = new javax.swing.GroupLayout(papel);
        papel.setLayout(papelLayout);
        papelLayout.setHorizontalGroup(
            papelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        papelLayout.setVerticalGroup(
            papelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(papel);
        papel.setBounds(480, 270, 100, 100);

        tesoura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tesoura.png"))); // NOI18N

        javax.swing.GroupLayout tesouraLayout = new javax.swing.GroupLayout(tesoura);
        tesoura.setLayout(tesouraLayout);
        tesouraLayout.setHorizontalGroup(
            tesouraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tesouraLayout.setVerticalGroup(
            tesouraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(tesoura);
        tesoura.setBounds(310, 260, 100, 100);

        btnpedra.setText("Pedra");
        btnpedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpedraActionPerformed(evt);
            }
        });
        jPanel1.add(btnpedra);
        btnpedra.setBounds(140, 380, 134, 60);

        btntesoura.setText("Tesoura");
        btntesoura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntesouraActionPerformed(evt);
            }
        });
        jPanel1.add(btntesoura);
        btntesoura.setBounds(300, 380, 134, 60);

        btnpapel.setText("Papel");
        btnpapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpapelActionPerformed(evt);
            }
        });
        jPanel1.add(btnpapel);
        btnpapel.setBounds(470, 380, 134, 60);

        pedraPc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pedra.png"))); // NOI18N

        javax.swing.GroupLayout pedraPcLayout = new javax.swing.GroupLayout(pedraPc);
        pedraPc.setLayout(pedraPcLayout);
        pedraPcLayout.setHorizontalGroup(
            pedraPcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pedraPcLayout.setVerticalGroup(
            pedraPcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(pedraPc);
        pedraPc.setBounds(160, 80, 100, 100);

        tesouraPc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tesoura.png"))); // NOI18N

        javax.swing.GroupLayout tesouraPcLayout = new javax.swing.GroupLayout(tesouraPc);
        tesouraPc.setLayout(tesouraPcLayout);
        tesouraPcLayout.setHorizontalGroup(
            tesouraPcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tesouraPcLayout.setVerticalGroup(
            tesouraPcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(tesouraPc);
        tesouraPc.setBounds(310, 80, 100, 100);

        papelPc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/papel.png"))); // NOI18N

        javax.swing.GroupLayout papelPcLayout = new javax.swing.GroupLayout(papelPc);
        papelPc.setLayout(papelPcLayout);
        papelPcLayout.setHorizontalGroup(
            papelPcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        papelPcLayout.setVerticalGroup(
            papelPcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(papelPc);
        papelPc.setBounds(470, 80, 100, 100);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("JOGADOR:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(121, 223, 113, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("PC:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(121, 46, 35, 29);

        reiniciar.setText("Reiniciar");
        reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarActionPerformed(evt);
            }
        });
        jPanel1.add(reiniciar);
        reiniciar.setBounds(630, 380, 134, 60);

        resultado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(resultado);
        resultado.setBounds(590, 40, 210, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Placar:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(620, 100, 90, 30);

        placarPL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(placarPL);
        placarPL.setBounds(630, 130, 160, 40);

        placarPC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(placarPC);
        placarPC.setBounds(630, 180, 150, 40);

        sair.setBackground(new java.awt.Color(255, 51, 0));
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jPanel1.add(sair);
        sair.setBounds(330, 470, 80, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 820, 510);

        setSize(new java.awt.Dimension(970, 555));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btntesouraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntesouraActionPerformed
        Random gera = new Random();
        pedra.setVisible(false);
        tesoura.setVisible(true);
        papel.setVisible(false);
        pedraPc.setVisible(false);
        tesouraPc.setVisible(false);
        papelPc.setVisible(false);
        btntesoura.setVisible(false);
        btnpapel.setVisible(false);
        btnpedra.setVisible(false);

        reiniciar.setVisible(true);
        int jogadaPc, jogadaplayer = 0;
        do {
            jogadaPc = gera.nextInt(3);
        } while (jogadaPc == 0);

        if (jogadaPc == 1) {
            pedraPc.setVisible(true);
            resultado.setText("PC ganhou!");
            contPC++;
        } else {
            tesouraPc.setVisible(true);
            resultado.setText("Jogador ganhou!");
            contPL++;
        }

        placarPL.setText("Jogador: " + contPL);
        placarPC.setText("PC: " + contPC);

    }//GEN-LAST:event_btntesouraActionPerformed

    private void btnpedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpedraActionPerformed
        Random gera = new Random();
        pedra.setVisible(true);
        tesoura.setVisible(false);
        papel.setVisible(false);
        pedraPc.setVisible(false);
        tesouraPc.setVisible(false);
        papelPc.setVisible(false);
        btntesoura.setVisible(false);
        reiniciar.setVisible(false);
        btnpapel.setVisible(false);
        btnpedra.setVisible(false);

        reiniciar.setVisible(true);
        int jogadaPc, jogadaplayer = 1;
        do {
            jogadaPc = gera.nextInt(3);
        } while (jogadaPc == 1);

        if (jogadaPc == 2) {
            papelPc.setVisible(true);
            resultado.setText("PC ganhou!");
            contPC++;
        } else {
            tesouraPc.setVisible(true);
            resultado.setText("Jogador ganhou!");
            contPL++;
        }

        placarPL.setText("Jogador: " + contPL);
        placarPC.setText("PC: " + contPC);
    }//GEN-LAST:event_btnpedraActionPerformed

    private void btnpapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpapelActionPerformed
        Random gera = new Random();
        pedra.setVisible(false);
        tesoura.setVisible(false);
        papel.setVisible(true);
        pedraPc.setVisible(false);
        tesouraPc.setVisible(false);
        papelPc.setVisible(false);
        btntesoura.setVisible(false);
        btnpapel.setVisible(false);
        btnpedra.setVisible(false);

        reiniciar.setVisible(true);
        int jogadaPc, jogadaplayer = 2;
        do {
            jogadaPc = gera.nextInt(3);
        } while (jogadaPc == 2);

        if (jogadaPc == 0) {
            tesouraPc.setVisible(true);
            resultado.setText("PC ganhou!");
            contPC++;
        } else {
            pedraPc.setVisible(true);
            resultado.setText("Jogador ganhou!");
            contPL++;
        }

        placarPL.setText("Jogador: " + contPL);
        placarPC.setText("PC: " + contPC);
    }//GEN-LAST:event_btnpapelActionPerformed

    private void reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarActionPerformed
        pedra.setVisible(true);
        tesoura.setVisible(true);
        papel.setVisible(true);
        pedraPc.setVisible(true);
        tesouraPc.setVisible(true);
        papelPc.setVisible(true);
        btntesoura.setVisible(true);
        btnpapel.setVisible(true);
        btnpedra.setVisible(true);
        btnpedra.setVisible(true);
        resultado.setText("");
        reiniciar.setVisible(false);
    }//GEN-LAST:event_reiniciarActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jokenPo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jokenPo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jokenPo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jokenPo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jokenPo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpapel;
    private javax.swing.JButton btnpedra;
    private javax.swing.JButton btntesoura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private org.edisoncor.gui.panel.PanelImage papel;
    private org.edisoncor.gui.panel.PanelImage papelPc;
    private org.edisoncor.gui.panel.PanelImage pedra;
    private org.edisoncor.gui.panel.PanelImage pedraPc;
    private javax.swing.JLabel placarPC;
    private javax.swing.JLabel placarPL;
    private javax.swing.JButton reiniciar;
    private javax.swing.JLabel resultado;
    private org.edisoncor.gui.button.ButtonNice sair;
    private org.edisoncor.gui.panel.PanelImage tesoura;
    private org.edisoncor.gui.panel.PanelImage tesouraPc;
    // End of variables declaration//GEN-END:variables
}
